# http端口号
http_port: 8989
# 允许的生产者列表
product_list:
  - project: svs
    allow_ip: # 消息来源ip限制
      - 127.0.0.1

  - project: sds
    allow_ip:
      - 127.0.0.1

msg_no_repeat_day: 4 # 整数 day 完全相同的消息 从发消息时刻到消息执行时刻后几天内不允许重复

get_point_sleep: 500 # 获取时间点后休息的时间 ms
msg_point_chan_len: 200 # 时间点通道长度
msg_bucket_chan_len: 500 # 消息bucket通道长度
msg_detail_chan_len: 1000 # 消息通道长度

bucket_coroutine_count: 500 # 处理bucket的协程数
msg_coroutine_count: 1000 # 执行message的协程数

# redis配置
redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 2 #数据库
  pool_size: 1000 # 连接池大小
  max_retries: 3 # 重试次数
  min_retry_backoff: 8 # 重试最小间隔 单位ms
  max_retry_backoff: 400 # 重试最大间隔 单位ms
  read_timeout: 1 # 读超时 单位s
  write_timeout: 2 # 写超时 单位s
  min_idle_conns: 200 # 最小空闲连接数
  pool_timeout: 5 # 客户端等待连接的时间 默认值为ReadTimeout + 1秒

# 命令列表
command_list:
  - cmd-sds-create-order.yaml # 另一个配置文件的路径
  - cmd-svs-notice-user.yaml
