# http端口号
http_port: 8989
# 允许的项目名字
product_list:
  - project: svs
    allow_ip:
      - 127.0.0.1

  - project: sds
    allow_ip:
      - 127.0.0.1

# redis配置
redis:
  host: 127.0.0.1
  port: 6379
#  password:
  db: 2 #数据库
  pool_size: 1000 # 连接池大小
  max_retries: 3 # 重试次数
  min_retry_backoff: 8 # 重试最小间隔 单位ms
  max_retry_backoff: 400 # 重试最大间隔 单位ms
  read_timeout: 1 # 读超时 单位s
  write_timeout: 2 # 写超时 单位s
#  min_idle_conns: 200 # 最小空闲连接数
#  pool_timeout: 5 # 客户端等待连接的时间 默认值为ReadTimeout + 1秒

# 命令列表
command_list:
  - commands/cmd-svs-create-order.yaml # 另一个配置文件的路径
  - commands/cmd-svs-notice-user.yaml
