# 属于哪个项目 如果sds发送了一个 svs:create:order 的命令就不会成功
# 如果多个羡慕的cmd重名了怎么办？？cmd上加前缀/后缀啊... 还能怎么办
project: svs
# 命令点
command: svs:notice:user
# 请求下游的接口列表 可以是多个下游消费
consumer_list:
  - host: 127.0.0.1:8959
    path: "/api/mytest/test/noticeuser"
    timeout: 600 #ms
    retry_times: 3 # 重试次数
    interval: 300 # 重试时间间隔 单位ms 和重试次数有关 第n次重试之前的休息时间是 interval*n
